name: CI - Python

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev 
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest || true

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Upload to JFrog PyPI
        run: |
          pip install twine
          echo "Uploading to: ${{ secrets.JFROG_URL }}/api/pypi/python-local/"
          twine upload \
            --repository-url "${{ secrets.JFROG_URL }}/api/pypi/python-local/" \
            -u "${{ secrets.JFROG_USERNAME }}" \
            -p "${{ secrets.JFROG_PASSWORD }}" \
            dist/*
